ThreeKingdomsEraApp/Models/AddOfficerForm.cs
namespace ThreeKingdomsEra.Models;

public class AddOfficerForm
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public int Birth { get; set; }
    public int Death { get; set; }
    public string Kingdom { get; set; }
    public string Bio { get; set; }
    
}

ThreeKingdomsEraApp/Models/EditOfficerForm.cs
namespace ThreeKingdomsEra.Models;

public class EditOfficerForm
{
    public string? Name { get; set; }
    public string? Surname { get; set; }
    public int Birth { get; set; }
    public int Death { get; set; }
    public string Kingdom { get; set; }
    public string Bio { get; set; }
}

ThreeKingdomsEraApp/Models/ErrorViewModel.cs
namespace ThreeKingdomsEra.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ThreeKingdomsEraApp/Models/OfficerDetailsViewModel.cs
using Core;

namespace ThreeKingdomsEra.Models;

public class OfficerDetailsViewModel
{
   public Officer Officer { get; set; }
}

ThreeKingdomsEraApp/Models/OfficersListViewModel.cs
using Core;

namespace ThreeKingdomsEra.Models;

public class OfficersListViewModel
{
    public List<Officer> Officers { get; set; }
}

ThreeKingdomsEraApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ThreeKingdomsEra.Models;

namespace ThreeKingdomsEra.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ThreeKingdomsEraApp/Controllers/OfficerController.cs
using Application;
using Application.Interfaces;
using Core;
using Microsoft.AspNetCore.Mvc;
using ThreeKingdomsEra.Models;

namespace ThreeKingdomsEra.Controllers;

[Route("[controller]/[action]")]
public class OfficerController : Controller
{
    private readonly IOfficerService _officerService;


    public OfficerController(IOfficerService officerService)
    {
        _officerService = officerService;
    }


    [HttpGet]
    public IActionResult List()
    {
        var officers = _officerService.GetOfficers();
        var viewModel = new OfficersListViewModel()
        {
            Officers = officers
        };
        return View(viewModel);
    }


    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }


    [HttpPost]
    public IActionResult Add(AddOfficerForm addOfficerForm)
    {
        var addOfficerDto = new AddOfficerDto()
        {
            Surname = addOfficerForm.Surname,
            Name = addOfficerForm.Name,
            Birth = addOfficerForm.Birth,
            Death = addOfficerForm.Death,
            Bio = addOfficerForm.Bio,
            Id = addOfficerForm.Id,
            Kingdom = addOfficerForm.Kingdom
        };
        var id = _officerService.AddOfficer(addOfficerDto);
        return RedirectToAction("List", new { id });
    }

    [HttpGet("{id:int}")]

    public IActionResult Edit(int id)
    {
        var officer = _officerService.GetOfficerById(id);
        var viewForm = new EditOfficerForm()
        {
            Name = officer.Name,
            Surname = officer.Surname,
            Birth = officer.Birth,
            Death = officer.Death,
            Kingdom = officer.Kingdom,
            Bio = officer.Bio,
        };
        return View(viewForm);
    }
    


    [HttpPost("{id:int}")]

    public IActionResult Edit(int id, EditOfficerForm editOfficerForm)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        var editOfficerDto = new EditOfficerDto()
        {
            Surname = editOfficerForm.Surname,
            Name = editOfficerForm.Name,
            Birth = editOfficerForm.Birth,
            Death = editOfficerForm.Death,
            Kingdom = editOfficerForm.Kingdom,
            Bio = editOfficerForm.Bio
        };

        _officerService.EditOfficer(id, editOfficerDto);
        return RedirectToAction("List");

    }


    public IActionResult Details(int id)
    {
        var officer = _officerService.GetOfficerById(id);
        if (officer is null)
        {
            return RedirectToAction(nameof(List));
        }
        var viewModel = new OfficerDetailsViewModel()
        {
            Officer = officer
        };
        
        return View(viewModel);
    }

    [HttpDelete("{id:int}")]
    public IActionResult Delete(int id)
    {
        _officerService.DeleteOfficer(id);
        return Ok();
    }
}

ThreeKingdomsEraApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ThreeKingdomsEraApp/Views/Officer/Add.cshtml
@model AddOfficerForm

@{
    {
        ViewBag.Title = "Add a new officer";
        Layout = "_Layout";
    }
}

<h2>Add a new officer</h2>

<form asp-action="Add">

    <div class="form-group">
        <label asp-for="Id" class="form-label">Officer Id</label>
        <input type="number" asp-for="Id" class="form-control"/>

    </div>

    <div class="form-group">
        <label asp-for="Surname" class="form-label">Surname</label>
        <input type="text" asp-for="Surname" class="form-control"/>
        <span asp-validation-for="Surname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Birth" class="form-label">Birth</label>
        <input type="number" asp-for="Birth" class="form-control"/>
        <span asp-validation-for="Birth" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Death" class="form-label">Death</label>
        <input type="number" asp-for="Death" class="form-control"/>
        <span asp-validation-for="Death" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="Kingdom" class="form-label">Kingdom</label>
        <input type="text" asp-for="Kingdom" class="form-control"/>
        <span asp-validation-for="Kingdom" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Bio" class="form-label">Bio</label>
        <input type="text" asp-for="Bio" class="form-control"/>
        <span asp-validation-for="Bio" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

ThreeKingdomsEraApp/Views/Officer/Details.cshtml
@model OfficerDetailsViewModel

@{
    Layout = "_Layout";
    var officer = Model.Officer;
}

<h2>@officer.Surname @officer.Name</h2>
<button class="btn btn-danger" id="delete-btn">Delete</button>

<dl class="row">

    <dt class="col-sm-3">Id</dt>
    <dd class="col-sm-9">@officer.Id</dd>

   
    <dt class="col-sm-3">Birth</dt>
    <dd class="col-sm-9">@officer.Birth</dd>


    <dt class="col-sm-3">Death</dt>
    <dd class="col-sm-9">@officer.Death</dd>

    <dt class="col-sm-3">Kingdom</dt>
    <dd class="col-sm-9">@officer.Kingdom</dd>

    <dt class="col-sm-3">Bio</dt>
    <dd class="col-sm-9">@officer.Bio</dd>


</dl>


<script>
 const deleteBtn = document.getElementById("delete-btn");
 deleteBtn.onclick = function(event) {
     const isOk = confirm('Are you sure about that?');
     if (isOk) {
         fetch("@Url.Action("Delete")" + "/@officer.Id", {
             method: 'DELETE'})
             .then((response) => {
                window.location.replace("@Url.Action("List")");
             });
     }
 };
</script>

ThreeKingdomsEraApp/Views/Officer/Edit.cshtml
@model EditOfficerForm

@{
    Layout = "_Layout";
}

<h2>Edit officer</h2>

<form asp-action="Edit">
    

    <div class="form-group">
        <label asp-for="Surname" class="form-label">Surname</label>
        <input type="text" asp-for="Surname" class="form-control"/>
        <span asp-validation-for="Surname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Birth" class="form-label">Birth</label>
        <input type="number" asp-for="Birth" class="form-control"/>
        <span asp-validation-for="Birth" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Death" class="form-label">Death</label>
        <input type="number" asp-for="Death" class="form-control"/>
        <span asp-validation-for="Death" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="Kingdom" class="form-label">Kingdom</label>
        <input type="text" asp-for="Kingdom" class="form-control"/>
        <span asp-validation-for="Kingdom" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Bio" class="form-label">Bio</label>
        <input type="text" asp-for="Bio" class="form-control"/>
        <span asp-validation-for="Bio" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

ThreeKingdomsEraApp/Views/Officer/List.cshtml
@model OfficersListViewModel

@{
    Layout = "_Layout";
}

<h2>List of Officers</h2>
<a class="btn btn-primary" asp-action="Add">Add officer</a>
<table class="table table-hover">
    <thead>
    <th>Id</th>
    <th>Surname</th>
    <th>Name</th>
    <th>Birth</th>
    <th>Death</th>
    <th>Kingdom</th>
    <th>Bio</th>

    </thead>
    <tbody>
    @foreach (var officer in Model.Officers)
    {
        <tr>
            <td>@officer.Id</td>
            <td>@officer.Surname</td>
            <td>@officer.Name</td>
            <td>@officer.Birth</td>
            <td>@officer.Death</td>
            <td>@officer.Kingdom</td>
            <td>@officer.Bio</td>
            <td>
                <a class="btn btn-info" role="button" asp-action="Edit" asp-route-id="@officer.Id">Edit</a>
                <a class="btn btn-info" role="button" asp-action="Details" asp-route-id="@officer.Id">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>

ThreeKingdomsEraApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ThreeKingdomsEraApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ThreeKingdomsEra.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ThreeKingdomsEraApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Officer" asp-action="List">Officers</a>
                    </li>
                </ul>
                
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - ThreeKingdomsEraApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>